--<DS_SCRIPT>
-- DESCRIO...: CRIANDO A ESTRUTURA PARA INTEGRAÇÃO DO ATENDIMENTO SOUL-MV COM O LABORATORIO COMPLAB
-- RESPONSAVEL.: FERNANDO GUARANY
-- DATA........: 24/04/2020
-- APLICAO...: SOUL-MV
-- VERSAO......: 2020.0.0
--</DS_SCRIPT>
--<USUARIO=DBAMV>

CREATE USER user_complab IDENTIFIED BY user_complab
DEFAULT TABLESPACE MV2000_D TEMPORARY TABLESPACE temp;
GRANT connect TO user_complab;
GRANT SELECT, UPDATE ON MVINTEGRA.complab TO user_complab;
