--<DS_SCRIPT>
-- DESCRIÇÃO..: Compilação das triggers de movimentação
-- RESPONSAVEL: Fernando Guarany
-- DATA.......: 25/05/2021
-- PRODUTO....: SUPRI
-- APLICAÇÃO..: MGES
-- ARTEFATO...: 
--</DS_SCRIPT>
--<USUARIO=DBAMV>

ALTER TRIGGER dbamv.TRG_U_MVTO_ESTOQUE ENABLE
/
ALTER TRIGGER dbamv.TRG_MVTO_ESTOQUE_VALIDA_ESTOQ ENABLE
/
ALTER TRIGGER dbamv.TRG_ORD_COM_CONTROLA_ORD ENABLE
/
ALTER TRIGGER dbamv.TRG_I_MVTO_ESTOQUE ENABLE
/
ALTER TRIGGER dbamv.TRG_MVTO_ESTOQUE_ATUALIZA_EMP ENABLE
/
ALTER TRIGGER dbamv.TRG_D_MVTO_ESTOQUE ENABLE
/
ALTER TRIGGER dbamv.TRG_I_MVTO_ESTOQUE_TRANSF ENABLE
/
ALTER TRIGGER dbamv.TRG_CTRL_TAM_SOUL_MVTO_ESTOQUE ENABLE
/
ALTER TRIGGER dbamv.TRG_MVTO_ESTOQUE_CHECA_MVTO ENABLE
/
ALTER TRIGGER dbamv.TRG_PREV_ORD_COM_AFT_UPD ENABLE
/
ALTER TRIGGER dbamv.TRG_CTRL_TAM_SOUL_ORD_COM ENABLE
/
ALTER TRIGGER dbamv.TRG_MVTO_KIT_PR_ATUALIZA_IE ENABLE
/
ALTER TRIGGER dbamv.TRG_PREV_ORD_COM_AFT_DEL ENABLE
/
ALTER TRIGGER dbamv.TRG_CTRL_TAM_SOUL_ORD_COM ENABLE
/
ALTER TRIGGER dbamv.TRG_PREV_ORD_COM_AFT_UPD ENABLE
/ 
ALTER TRIGGER dbamv.TRG_MVTO_KIT_PR_ATUALIZA_SALDO ENABLE
/  