------------------------------------------ ORACLE ------------------------------------------
--<DS_SCRIPT>
-- DESCRICAO...: Adicionando nova tabela no modulo PSSD
-- RESPONSAVEL.: Fernando Guarany
-- DATA........: 19/08/2020
-- APLICAO...: SOUL - PROJETO BH
-- VERSAO......: A PARTIR DA VERSÃO 2020.0.0
--</DS_SCRIPT>
--<USUARIO=DBAMV>

CREATE TABLE dbamv.HIST_PREGRESSA(
COD_HIST NUMBER PRIMARY KEY NOT NULL,
REDE_PUBLICA_PN VARCHAR2(1),
DESC_INSTI_PUBLICA_PN VARCHAR2(100),
NUM_CONSULTAS_PUBLICA_PN NUMBER,
REDE_PRIVADA_PN VARCHAR(1),
DESC_INSTI_PRIV_PN VARCHAR2(100),
NUM_CONSULTAS_PRIV_PN NUMBER,
NAO_REALIZADO_PN VARCHAR2(1),
ORIENTACAO_AMAMENT_PN VARCHAR2(1),
TRAT_GESTACAO VARCHAR2(100),
REDE_PUBLICA_P VARCHAR2(1),
DESC_INSTI_PUBLICA_P VARCHAR2(100),
REDE_PRIVADA_P VARCHAR(1),
DESC_INSTI_PRIV_P VARCHAR2(100),
PARTO_NORMAL VARCHAR2(1),
PARTO_CESARI VARCHAR2(1),
PARTO_FORCEPS VARCHAR2(1),
PESO_GESTACAO_INICIAL VARCHAR2(7),
PESO_GESTACAO_FINAL VARCHAR2(7),
ALTURA VARCHAR2(6),
IDADE_GESTACIONAL_SEMANA VARCHAR2(5),
IDADE_GESTACIONAL_DIAS VARCHAR2(5)
);
/

ALTER TABLE dbamv.HIST_PREGRESSA ADD CD_PACIENTE NUMBER(8);
/

ALTER TABLE DBAMV.HIST_PREGRESSA ADD CONSTRAINT FK_PACI_DOA
    FOREIGN KEY (CD_PACIENTE)
    REFERENCES DBAMV.PACIENTE(CD_PACIENTE);

CREATE PUBLIC SYNONYM HIST_PREGRESSA FOR dbamv.HIST_PREGRESSA;
/

GRANT ALL ON dbamv.HIST_PREGRESSA TO dbamv, dbamvfor, sigsaudej, mv2000;
/

create sequence SEQ_HIST_PRE
minvalue 1
maxvalue 9999999999
start with 1
increment by 1
nocache
cycle;
/

COMMENT ON COLUMN DBAMV.HIST_PREGRESSA.COD_HIST IS 'Sequence da tabela';
/
COMMENT ON COLUMN DBAMV.HIST_PREGRESSA.REDE_PUBLICA_PN IS 'Campo valida se pre natal foi realizado em rede publica';
/
COMMENT ON COLUMN DBAMV.HIST_PREGRESSA.REDE_PUBLICA_PN IS 'Campo valida se pre natal foi realizado em rede publica';
/
COMMENT ON COLUMN DBAMV.HIST_PREGRESSA.DESC_INSTI_PUBLICA_PN IS 'Campo valida se pre natal foi realizado em rede publica';
/
COMMENT ON COLUMN DBAMV.HIST_PREGRESSA.NUM_CONSULTAS_PUBLICA_PN IS 'Campo informa o numero de consultas realizadas na rede publica';
/
COMMENT ON COLUMN DBAMV.HIST_PREGRESSA.REDE_PRIVADA_PN IS 'Campo valida de pre natal foi realizado em rede privada';
/









